/* version.c */
/* Autogenerated by Makefile - DO NOT EDIT */

const char *version_string = "1.15";
const char *compilation_string = "/home/klee/klee/scripts/klee-gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC=\"/usr/local/etc/wgetrc\" -DLOCALEDIR=\"/usr/local/share/locale\" -I. -I../../src -I../lib -I../../lib -g";
const char *link_string = "/home/klee/klee/scripts/klee-gcc -g -lgnutls -lz -lidn -lrt ftp-opie.o gnutls.o ../lib/libgnu.a";
